# These are supported funding model platforms

github: [nitanmarcel] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: [paypal.me/marcelalexandrunitan, revolut.me/nitanmarcel]
